plot(
    x = 1:10,
    y = 10:1,
    main = "A demonstration",
    cex.main = 3,
    font.main = 2,
    xlab = "The x-axis",
    ylab = "The y-axis",
    col.lab = "blue",
    type = "b",
    col = "red",
    lty = "dashed",
    lwd = 2,
    pch = "&",
)